export const WELCOME = "/kezdolap"
export const SPECIAL_OFFER = "/ajanlatok"
export const ROOMS = "/szobak"
export const INTRO = "/bemutatkozas"
export const CERTIFICATES = "/tanusitvanyok"
export const EVENTS = "/rendezvenyek"
export const FOODS = "/etelek"
export const SETTINGS = "/beallitasok"
export const SERVICES = "/szolgaltatasaink"
export const CALENDAR = "/naptar"
export const RESERVATIONS = "/foglalasok"
export const FEEDBACKS = "/visszajelzesek"
export const STATS = "/statisztikak"


export const EDIT = "szerkeszt"
export const UPLOAD = "feltoltes"
export const HANDLED = "kezelt"
export const READ = "olvasott"
export const UNREAD = "olvasatlan"
